In [ ]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# importing Dataset from Local drive
from google.colab import files
Uploaded=files.upload()

Saving DATASET education.xlsx to DATASET education.xlsx


In [ ]:
dataset = pd.read_excel('/content/drive/My Drive/DATASET education.xlsx')

In [ ]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(119, 10)


In [ ]:
#Print Imformation about data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   10th               119 non-null    float64
 1   12th               119 non-null    float64
 2   B.Tech             119 non-null    float64
 3   7-SEM              119 non-null    float64
 4   6-SEM              119 non-null    float64
 5   5-SEM              119 non-null    float64
 6   Final Performance  119 non-null    float64
 7   Medium             119 non-null    int64  
 8   Package            119 non-null    object 
 9   Placed             119 non-null    int64  
dtypes: float64(7), int64(2), object(1)
memory usage: 9.4+ KB


In [ ]:
print(dataset)

      10th  12th  B.Tech  7-SEM  ...  Final Performance  Medium   Package  Placed
0    74.83  75.2   72.80  67.04  ...              56.77       2    5.0LPA       1
1    89.30  80.8   69.60  73.49  ...              61.38       1      0LPA       0
2    79.83  75.4   58.70  62.82  ...              51.81       2      0LPA       0
3    68.40  59.6   54.40  65.17  ...              54.84       1   10.0LPA       1
4    79.80  69.8   74.45  76.24  ...              67.80       1  3.36 LPA       1
..     ...   ...     ...    ...  ...                ...     ...       ...     ...
114  76.00  82.6   68.25  56.96  ...              46.25       1   3.8 LPA       1
115  83.60  75.8   70.10  64.83  ...              53.92       1   3.6 LPA       1
116  89.30  68.4   77.55  67.57  ...              58.27       1   3.8 LPA       1
117  89.30  72.0   74.90  65.10  ...              56.63       1      0LPA       0
118  53.20  71.6   71.00  40.08  ...              34.48       1  2.40 LPA       1

[119 rows x 10 

In [ ]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:, 0:8].values
# Extracting dependent variable:
y = dataset.iloc[:, 9].values


In [ ]:
print(X)

[[74.83 75.2  72.8  67.04 34.53 18.4  56.77  2.  ]
 [89.3  80.8  69.6  73.49 31.81 21.5  61.38  1.  ]
 [79.83 75.4  58.7  62.82 31.44  5.38 51.81  2.  ]
 [68.4  59.6  54.4  65.17 35.92 10.92 54.84  1.  ]
 [79.8  69.8  74.45 76.24 44.5  44.2  67.8   1.  ]
 [76.   74.   51.6  70.59 36.52 79.85 66.05  1.  ]
 [77.33 65.6  66.3  73.34 49.02 23.09 64.22  1.  ]
 [63.5  59.6  59.9  50.74 36.22  4.94 43.66  1.  ]
 [89.17 83.8  70.1  55.18 42.92 10.5  48.58  2.  ]
 [87.4  83.8  79.55 69.53 51.96 24.25 62.01  1.  ]
 [81.7  61.4  68.15 61.32 44.05 37.44 56.06  1.  ]
 [96.83 87.2  72.85 59.69 40.36 28.87 53.39  1.  ]
 [66.5  57.8  54.05  0.94 20.18 13.52  5.35  1.  ]
 [62.7  65.   27.8   0.96  3.24  0.    1.23  1.  ]
 [85.5  67.   66.95 55.6  37.24  3.15 47.21  1.  ]
 [93.1  86.   81.55 63.95 52.26 20.09 57.53  1.  ]
 [58.   60.6  55.95 41.36 31.21  2.95 35.75  2.  ]
 [66.5  75.2  74.55 73.76 46.46 37.97 65.65  1.  ]
 [68.4  59.6  63.45 70.87 34.26  9.87 58.66  1.  ]
 [87.4  85.4  66.35 60.51 41.49

In [ ]:
print(y)

[1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 1 1 0 0 0 1 1 1
 1 0 1 0 1 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1
 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1]


In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

In [ ]:
print(X_test)

In [ ]:
print(y_test)

[0 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1]


In [ ]:
print(y_train)

[1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1 0 1
 1 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0]


In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 5.15384898e-01  1.98834927e+00  3.84640577e-01  6.17415734e-01
   1.75677284e-01 -2.76414019e-01  5.28392939e-01  1.91942974e+00]
 [ 6.67535014e-01 -1.73812159e-01  7.55602697e-01  1.32350678e+00
  -1.88791741e+00 -1.09828855e+00  7.32671476e-01 -5.20988072e-01]
 [ 4.50177706e-01  1.59522901e+00  7.92176427e-01 -4.56958528e-02
  -7.56761799e-01  3.11598328e-01 -9.19049048e-02 -5.20988072e-01]
 [-3.02753923e+00 -1.80526123e+00 -7.54369875e-01 -1.32126467e+00
   4.18067772e-01  8.22962062e-01 -9.80843017e-01 -5.20988072e-01]
 [-1.28868076e+00 -1.21558085e+00 -1.31342546e+00  2.01436012e-01
  -1.85724749e-01 -9.80238502e-01 -1.44842717e-02 -5.20988072e-01]
 [-6.36608835e-01 -8.42116600e-01 -6.02850136e-01 -1.94588964e-01
   2.08432756e-01 -6.84833631e-01 -2.63536188e-01 -5.20988072e-01]
 [-2.67101411e-01 -6.25900457e-01 -6.99186398e-02  8.28475556e-01
   1.24459750e+00 -2.99352654e-01  8.60462160e-01 -5.20988072e-01]
 [ 1.75432156e+00  6.51740385e-01  5.10036224e-01  1.58456557e-01
  -

In [ ]:
print(X_test)

[[-8.53966144e-01 -1.09764477e+00 -6.39423866e-01  4.39357993e-01
  -5.23106104e-01 -7.34627255e-01  1.93525381e-01 -5.20988072e-01]
 [-1.50603807e+00 -1.93468172e-01 -1.02083562e+00 -4.25603533e-01
   9.03940596e-01 -1.01828307e+00 -4.31436356e-01 -5.20988072e-01]
 [ 1.75432156e+00  1.18245273e+00  5.88408502e-01  1.44860769e+00
   1.96849341e+00 -9.23731131e-01  1.40613771e+00 -5.20988072e-01]
 [ 1.08737781e+00  1.16279672e+00  3.27167573e-01 -5.65286761e-01
   5.78569581e-01 -1.00373662e+00 -5.98403745e-01  1.91942974e+00]
 [ 4.76489380e-01  7.89332475e-01  2.12221564e-01  8.37685439e-01
  -1.24581203e-01 -2.26934709e-03  7.30805919e-01  1.91942974e+00]
 [-1.10564303e+00 -7.43836535e-01 -1.21937873e+00 -2.39870889e-01
  -6.09362178e-01 -2.24105883e-02 -3.01780115e-01  1.91942974e+00]
 [-1.84923382e+00 -1.21558085e+00 -7.38695419e-01 -9.06052437e-01
  -1.52969278e-01 -1.31480690e+00 -1.05733087e+00 -5.20988072e-01]
 [ 2.32820398e-01 -1.03867673e+00  1.23399648e-01 -9.40477394e-02
   

In [ ]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [ ]:
print(y_pred)

[0 0 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 0 1 0 1 1 1 0 1 1]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[10  3]
 [ 4 13]]


In [ ]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 76.67


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))

Precision: 81.250


In [ ]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Recall: 76.471


In [ ]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Recall: 76.471


In [ ]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 78.788


In [ ]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/Naive_Bayes_education_model.pkl', 'wb'))
# Saving model to disk


[INFO] Saving model...


In [ ]:
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/Naive_Bayes_education_model.pkl','rb'))
# Use the loaded pickled model to make predictions
model.predict(X_test)

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1])

In [ ]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/FDP/naivebayes_model.sav'
joblib.dump(classifier, filename)

# some time later...

# load the model from disk
randomforest_model = joblib.load(filename)
result = randomforest_model.score(X_test, y_test)
print(result)

0.7666666666666667


In [ ]:
marksinsecondary =  89.30#@param {type:"number"}
marksinhighersecondary =  72.00#@param {type:"number"}
aggregatemarks =  74.90#@param {type:"number"}
VIIsemmarks =  67#@param {type:"number"}
VIsemmarks =  67#@param {type:"number"}
Vsemmarks =  67#@param {type:"number"}
finalperformance = 56.630 #@param {type:"number"}
medium =  1#@param {type:"number"}
   # load the model from disk
naive_Bayes_model = joblib.load(filename)

output=naive_Bayes_model.predict([[marksinsecondary, marksinhighersecondary ,aggregatemarks,VIIsemmarks, VIsemmarks,Vsemmarks,finalperformance, medium]])
print("Placed =", output)
if output==[1]:
  print( 'Student will be Placed')
else:
  print('Student will not be placed')

Placed = [1]
Student will be Placed


In [ ]:
!pip install flask-ngrok

In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%mkdir templates -p

In [ ]:
%%writefile templates/index.html
<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
<title>Machine Learning Lab Experiment Deployment</title>
<meta charset="UTF-8">
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<style><!DOCTYPE html>

h1 {text-align: center;}
h2 {text-align: center;}
h3 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>

<body>


<div class="" style="background-color:blue;" >
<div class="clearfix">

<div class="col-md-12">
<center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center>
<center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center>
<center><p style="font-size:25px;color:white;margin-top:10px;">Machine Learning Lab Experiment Deployment</p></center>
</div>
</div>
</div>

<div class="login">
<h2 >Naive Bayes classification for prediction of Placement</h2>
<h4>Developed by Deepak Moud</h4>
<!-- Main Input For Receiving Query to our ML -->
<form action="{{ url_for('predict')}}"method="get">
<div class="form-floating mb-3">
<input type="number" class="form-control" id="floatingInput" name="percentage10" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter 10th Class Percentage</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" class="form-control" id="floatingInput" name="percentage12" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter 12th Class Percentage</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" name="BTechpercentage" class="form-control" id="floatingInput" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter BTech Aggregate</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" name="marks7sem" class="form-control" id="floatingInput" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter VII Sem Placement Performance Marks</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" name="marks6sem" class="form-control" id="floatingInput" placeholder="Percentage"min="1" max="100" required="required" />
<label for="floatingInput">Enter VI Sem Placement Performance Marks</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" name="marks5sem" class="form-control" id="floatingInput" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter V Sem Placement performance Marks</label>
</div>
<br>
<div class="form-floating mb-3">
<input type="number" name="finalperformance" class="form-control" id="floatingInput" placeholder="Percentage" min="1" max="100" required="required" />
<label for="floatingInput">Enter Final Performance Marks</label>
</div>
<br>
<label for="Medium">Choose a Medium</label>

<select name="medium" id="medium">
  <option value="1">Hindi</option>
  <option value="2">English</option>

</select>
<br>
<br>
<br>
<button type="submit" class="btn btn-primary btn-block btn-large">Predict Student Placement</button>
</form>
<br>
<br>
{{ prediction_text }}

</div>

<div class="" style="background-color:blue;" >
<div class="clearfix">

<div class="col-md-12">
 <center><p style="font-size:25px;color:white;margin-top:20px;">Machine Learning Lab</p></center>
</div>
</div>
</div>
</body>
</html>



Overwriting templates/index.html


In [ ]:
!pip install flask-ngrok
import numpy as np
from flask import Flask, request, jsonify, render_template
from flask_ngrok import run_with_ngrok
import pickle
import pandas as pd
dataset= pd.read_excel('/content/drive/My Drive/DATASET education.xlsx')
X = dataset.iloc[:, 0:8].values
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

app = Flask(__name__)
model = pickle.load(open('/content/drive/My Drive/Naive_Bayes_education_model.pkl','rb'))
run_with_ngrok(app)

@app.route('/')
def home():

    return render_template("index.html")

@app.route('/predict',methods=['GET'])
def predict():



    '''
    For rendering results on HTML GUI
    '''
    percentage10 = int(request.args.get('percentage10'))
    percentage12 = int(request.args.get('percentage12'))
    BTechpercentage = int(request.args.get('BTechpercentage'))
    marks7sem = int(request.args.get('marks7sem'))
    marks6sem = int(request.args.get('marks6sem'))
    marks5sem = int(request.args.get('marks5sem'))
    finalperformance = int(request.args.get('finalperformance'))
    medium = int(request.args.get('medium'))
    prediction = model.predict([[percentage10,percentage12, BTechpercentage, marks7sem, marks6sem,marks5sem, finalperformance, medium ]])
    print(prediction)
    if prediction==[1]:
        output='Placed'
    else:
        output='Not Placed'

    return render_template('index.html', prediction_text='Model has predicted student will be : {}'.format(output))


app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://7aff1057844c.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [09/Apr/2021 13:47:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Apr/2021 13:47:06] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [09/Apr/2021 13:47:25] "GET /predict?percentage10=67&percentage12=55&BTechpercentage=67&marks7sem=56&marks6sem=78&marks5sem=89&finalperformance=56&medium=2 HTTP/1.1" 200 -


[1]
